### ISSUE TITLE
Incorrect labels after relating to grafana-agent rev 38

### ISSUE THREAD

**Issue by przemeklal** [canonical/hardware-observer-operator#158]
After relating hw-obs (tried rev 25 and rev 29) to grafana-agent rev 38, the labels are incorrect.

All hw-obs metric series use identical labels, especially problematic is that all of them use `instance="localhost:10200"` and `juju_unit` label doesn't exist anymore.

This makes it impossible to distinguish between metrics coming from different machines.

This is what the relevant `metrics` section in /etc/grafana-agent.yaml looks like:
```
metrics:
  configs:
  - name: agent_scraper
    remote_write:
    - tls_config:
        insecure_skip_verify: true
      url: http://<cos_traefik_ip>/cos-prometheus-0/api/v1/write
    scrape_configs:
    - job_name: hardware-observer_0_default
      metrics_path: /metrics
      static_configs:
      - labels:
          juju_application: hardware-observer
          juju_model: openstack
          juju_model_uuid: a2aaf764-adb9-43ae-9330-e5909e6891c1
        targets:
        - localhost:10200
  global:
    scrape_timeout: 60s
  wal_directory: /tmp/agent/data
```

This is a critical issue.
